const BACKEND_ROOT = import.meta.env.VITE_BACKEND_ROOT
const SOCKET_ROOT = import.meta.env.VITE_SOCKET_ROOT
const ENDPOINT_LOGIN = import.meta.env.VITE_ENDPOINT_LOGIN

export { BACKEND_ROOT, ENDPOINT_LOGIN, SOCKET_ROOT}